# Generated by Django 4.2.6 on 2023-10-24 06:57

import discounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expire_date',
            field=models.DateField(default=discounts.models.add_weak),
        ),
    ]
