# Generated by Django 4.2.6 on 2023-10-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
