# Generated by Django 4.2.6 on 2023-10-21 18:36

import discounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_point_expire_date_alter_voucher_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='expire_date',
            field=models.DateField(default=discounts.models.add_year),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expire_date',
            field=models.DateField(default=discounts.models.add_year),
        ),
    ]
