# Generated by Django 4.2.6 on 2023-10-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
