# Generated by Django 4.2.6 on 2023-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chat',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
