# Generated by Django 4.2.6 on 2023-10-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='project_id',
        ),
    ]
