# Generated by Django 4.2.6 on 2023-10-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_id_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='certificates/')),
            ],
        ),
    ]
