# Generated by Django 4.2.6 on 2023-10-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
