# Generated by Django 4.2.6 on 2023-11-23 13:31

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_certificates_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.project_image_path),
        ),
    ]
